server:
  port: 8090

spring:
  application:
    name: users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: egorik1234566
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

token:
  signing:
    key: eryejgfkgrekgrelgrhgfhgfhtehghrfteghfbvcbmefdsewtrw
    lifetime: 3600000
