spring:
  application:
  name: profile-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: egorik1234566
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    compatibility-verifier:
      enabled: false
server:
  port: 8070

management:
  tracing:
    sampling:
      probability: 1.0

token:
  signing:
    key: eryejgfkgrekgrelgrhgfhgfhtehghrfteghfbvcbmefdsewtrw
    lifetime: 3600000



